signup:
    method: post
    url: https://api.parse.com/1/login

login:
    method: get
    url: https://api.parse.com/1/login

retrieveUser:
    method: get
    url: https://api.parse.com/1/users/%userKey%
